[workspace]
resolver = "2"
members = []

[package]
name = "git-branch-grep"
version = "0.1.0"
authors = ["Daniel Beckwith <djbsnx@gmail.com>"]
edition = "2024"

[dependencies]
anyhow = "1.0.97"
argh = "0.1.13"
atty = "0.2.14"
git2 = "0.20.1"
regex = "1.11.1"
