[workspace]
resolver = "2"
members = []

[package]
name = "git-branch-grep"
version = "0.1.0"
authors = ["Daniel Beckwith <djbsnx@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.41"
argh = "0.1.4"
git2 = "0.13.20"
regex = "1.5.4"
